#!/bin/bash

gh issue create --title "Core/config ve core/utils klasörlerinin boş dosyalarıyla birlikte hazırlanması" --label "todo" --body ""
gh issue create --title "Domain katmanında users, chatbot ve mentors paketlerinin oluşturulması" --label "todo" --body ""
gh issue create --title "Application/services içinde temel service iskeletinin eklenmesi" --label "todo" --body ""
gh issue create --title "Infrastructure/orm, infrastructure/api ve infrastructure/ai klasörlerinin eklenmesi" --label "todo" --body ""
gh issue create --title "main.py dosyasına FastAPI başlangıç kodunun eklenmesi" --label "todo" --body ""
gh issue create --title "React frontend klasör yapısının oluşturulması" --label "todo" --body ""
gh issue create --title "src/components/Chat klasöründe ChatWindow, ChatMessage ve ChatInput componentlerinin oluşturulması" --label "todo" --body ""
gh issue create --title "API client için services/apiClient.js dosyasının hazırlanması" --label "todo" --body ""
gh issue create --title "ChatContext'in oluşturulması" --label "todo" --body ""
gh issue create --title "Login ve Chatbot sayfalarının minimal iskeletlerinin eklenmesi" --label "todo" --body ""

#!/bin/bash

gh issue create --title "AuthService: Register & Login endpoints (basic)" --label "todo" --body $'Amaç:\nBasit kullanıcı kayıt ve giriş akışını sağlayacak /auth/register ve /auth/login endpointlerini oluşturmak.\n\nKabul Kriterleri:\n- /auth/register POST: email, password alır; basit doğrulama yapar; memory-based store\'a ekler.\n- /auth/login POST: email, password alır; doğrulama başarılıysa basit success JSON döner.\n- Parolalar plaintext depolanmaz (basit hash kullanımı önerilir, örnek: werkzeug veya hashlib).\n\nAdımlar/Implementation:\n1) backend/application/services içinde AuthService iskeleti oluştur.\n2) backend/domain/users modeline temel alanlar ekle (email, password_hash, id, created_at).\n3) backend/infrastructure/api içine auth_router ekle ve iki endpointi tanımla.\n4) Basit in-memory store (dictionary) kullan; ileride DB ile replace edilecek.\n\nNotlar:\n- Bu aşamada token/JWT gerekmiyor; ileride ekleyeceğiz.\n- Error handling ve uygun HTTP status kodlarını kullan.'"

gh issue create --title "User domain: User model + DTOs" --label "todo" --body $'Amaç:\nUser entity/modelini ve transfer objelerini (DTO) tanımlamak.\n\nKabul Kriterleri:\n- backend/domain/users içinde User dataclass veya pydantic model hazırlanmış.\n- DTO\'lar: UserCreate, UserRead (göndermek için) tanımlı.\n\nAdımlar/Implementation:\n1) backend/domain/users/models.py oluştur: User, UserCreate, UserRead.\n2) Fieldler: id (uuid), email, password_hash, role, created_at.\n3) Basit örnek unit test veya docstring ile modelin kullanılabilirliği gösterilsin.\n\nNotlar:\n- Pydantic kullanımı tercih edilir (FastAPI ile uyumlu).'"

gh issue create --title "ChatbotService: sendMessage skeleton" --label "todo" --body $'Amaç:\nChatbot için sendMessage fonksiyonunun temel iskeletini oluşturmak; şimdilik LLM bağlı değil, placeholder cevap dönecek.\n\nKabul Kriterleri:\n- backend/application/services/chatbot_service.py içinde send_message(user_id, message) fonksiyonu var.\n- Fonksiyon gelen mesajı loglayıp: \"Mesaj alındı: <mesaj>\" şeklinde dönüş sağlıyor.\n\nAdımlar/Implementation:\n1) servis sınıfı iskeleti oluştur (class ChatbotService).\n2) send_message fonksiyonu implement edilsin.\n3) Test endpoint ile entegre edilecek (/chat/send).\n\nNotlar:\n- İleride OpenAI/Supabase bağlanınca bu fonksiyon genişletilecek.'"

gh issue create --title "API endpoint: POST /chat/send (basic)" --label "todo" --body $'Amaç:\nFrontend\'in mesaj gönderip bot cevabı alabileceği basit endpoint.\n\nKabul Kriterleri:\n- POST /chat/send JSON alır: { \"user_id\": \"...\", \"message\": \"...\" }\n- Endpoint ChatbotService.send_message çağırır ve returned cevabı JSON döner.\n\nAdımlar/Implementation:\n1) backend/infrastructure/api/chat_router.py oluştur.\n2) router\'a /chat/send endpoint ekle.\n3) Endpoint validate için pydantic model kullan (ChatRequest).\n4) Return format: { \"reply\": \"...\" }\n\nNotlar:\n- Hata durumlarında 4xx/5xx uygun dönüşler verilsin.'"

gh issue create --title "Frontend: Login page functional (basic API hookup)" --label "todo" --body $'Amaç:\nReact Login sayfasını backend auth endpointine bağlamak: form verisi POST ile gönderilecek ve sonuç işlenecek.\n\nKabul Kriterleri:\n- src/pages/Login.jsx formu çalışır durumda.\n- Submit ile /auth/login çağrılır (fetch/axios) ve gelen response UI\'da gösterilir.\n\nAdımlar/Implementation:\n1) src/pages/Login.jsx içinde form hazırlansın (email, password).\n2) services/apiClient.js üzerinden login isteği atılsın.\n3) Başarılı/başarısız durumlar kullanıcıya gösterilsin.\n\nNotlar:\n- Gerçek auth yoksa mock success response kabul edilir.'"

gh issue create --title "Frontend: ChatWindow -> sends message to backend" --label "todo" --body $'Amaç:\nChat arayüzünden gönderilen mesajın backend /chat/send endpointine ulaşması ve dönen cevabın ekranda gösterilmesi.\n\nKabul Kriterleri:\n- ChatInput\'tan gönderilen mesaj backend\'e POST edilir.\n- Dönen \"reply\" mesaj ChatWindow\'da görünür.\n\nAdımlar/Implementation:\n1) src/components/Chat/ChatInput.jsx gönderme fonksiyonunu apiClient kullanacak şekilde düzenle.\n2) ChatWindow mesaj listesine backend cevabını push et.\n3) Loading state (isLoading) göster.\n\nNotlar:\n- Hatalı isteklerde kullanıcıya uyarı verilsin.'"

gh issue create --title "ChatContext: global state for messages & sendMessage()" --label "todo" --body $'Amaç:\nUygulama genelinde chat mesajlarını yönetecek context ve sendMessage fonksiyonunun oluşturulması.\n\nKabul Kriterleri:\n- src/context/ChatContext.jsx içinde context sağlanıyor.\n- messages dizisi, sendMessage fonksiyonu ve isLoading state mevcut.\n\nAdımlar/Implementation:\n1) ChatContext wrapper oluştur ve App\'e sar.\n2) sendMessage fonksiyonu backend çağrısını yapıp messages\'a eklesin.\n3) Child componentler (ChatWindow vb.) context konsumeli şekilde çalışsın.\n\nNotlar:\n- State yönetimi basit React Context ile yapılacak; ileride Zustand vb. eklenebilir.'"

gh issue create --title "UI: MessageBubble component düzenlemesi" --label "todo" --body $'Amaç:\nMesaj baloncuklarının görsel düzeni: kullanıcı/bot ayrımı, timestamp gösterimi.\n\nKabul Kriterleri:\n- src/components/Chat/ChatMessage.jsx içinde kullanıcı mesajı sağda, bot sol taraf.\n- Mesaj metni ve saat bilgisi gösterilsin.\n\nAdımlar/Implementation:\n1) ChatMessage component layout tasarlanacak (CSS sınıfları kullanılarak).\n2) timestamp formatlanıp gösterilecek (örn. HH:MM).\n3) Responsive davranış test edilecek.\n\nNotlar:\n- Stil için mevcut styles/global.css kullanılacak.'"

gh issue create --title "Infrastructure: OpenAI client skeleton (no keys yet)" --label "todo" --body $'Amaç:\nOpenAI/LLM entegrasyonu için altyapı dosyası oluşturmak; fakat bu aşamada gerçek anahtar yok, sadece iskelet.\n\nKabul Kriterleri:\n- backend/infrastructure/ai/openai_client.py oluşturulsun.\n- Class OpenAIClient { def send(self, message): return \"LLM not connected\" }\n\nAdımlar/Implementation:\n1) Dosya ve sınıf iskeleti yazılsın.\n2) ChatbotService bu client ile entegre edilmeye hazır olsun (dependency injection).\n\nNotlar:\n- Gerçek anahtarlar .env dosyasına eklenecek, bu issue scope\'unda değildir.'"

gh issue create --title ".env.example dosyalarının oluşturulması (backend + frontend)" --label "todo" --body $'Amaç:\nProje için örnek environment dosyaları oluşturmak; geliştiricilerin hangi değişkenleri dolduracaklarını bilmeleri amaçlanıyor.\n\nKabul Kriterleri:\n- backend/.env.example ve frontend/.env.example dosyaları eklenmiş.\n- İçerik: BACKEND_PORT, API_URL, DATABASE_URL (placeholder), FIREBASE_DB_URL (placeholder), VITE_API_URL vb.\n\nAdımlar/Implementation:\n1) backend/.env.example dosyasını oluştur ve gerekli anahtar isimlerini ekle.\n2) frontend/.env.example (Vite veya CRA kullanıyorsan REACT_APP_ prefix) ekle.\n3) README\'ye environment setup adımı kısa not olarak ekle.\n\nNotlar:\n- Gerçek secretlar asla repo\'ya pushlanmasın; GitHub Secrets veya hosting secrets kullanılacak.'"

echo "All sprint-2 issues created."


